[profile.default]
auto_detect_solc = true
src = "src"
out = "out"
libs = ["lib"]
test = "test"
bytecode_hash = "none"
cbor_metadata = false
evm_version = "cancun"
optimizer = true
optimizer_runs = 1_000_000
viaIR = true

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY_V2}" }
base = { key = "${ETHERSCAN_API_KEY_V2}" }

[fmt]
number_underscore = "thousands"
