[profile.default]
src = "src"
test = "tests"
libs = ["lib"]
out = "out"
optimizer = true
solc_version = "0.8.30"
evm_version = "cancun"
via_ir = true

[rpc_endpoints]
base-sepolia = "${BASE_SEPOLIA_RPC_URL}"
base = "${BASE_RPC_URL}"

[etherscan]
base-sepolia = { key = "${ETHERSCAN_API_KEY_V2}" }
base = { key = "${ETHERSCAN_API_KEY_V2}" }

[fmt]
tab_width = 2
line_length = 120
bracket_spacing = true
quote_style = "double"
number_underscore = "thousands"
multiline_func_header = "params_first"
ignore = ["lib/**"]
